name: Multi Job Workflow

on:
  schedule:
    - cron: '0 * * * *'  # Triggar varje timme

jobs:
  job1:
    runs-on: ubuntu-latest

    env:
      GREETING: "Hello"
      TARGET: "World"
      MY_SECRET: ${{ secrets.MY_SECRET }}  # Ersätt MY_SECRET med namnet på din secret

    steps:
      - name: Print greeting from Job 1
        run: |
          echo "${{ env.GREETING }} ${env.TARGET}!"
          echo "Secret value: ${{ secrets.MY_SECRET }}"

  job2:
    runs-on: ubuntu-latest
    needs: job1  # Detta jobb behöver att job1 körs klart först

    env:
      FAREWELL: "Goodbye"
      TARGET: "Everyone"

    steps:
      - name: Print farewell from Job 2
        run: |
          echo "${{ env.FAREWELL }} ${env.TARGET}!"
          echo "Greeting from Job 1: ${{ needs.job1.outputs.greeting }}"
